# Generated by Django 6.0.6 on 2026-07-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='تماس با ما', max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('working_hours_sat_wed', models.CharField(blank=True, max_length=50, verbose_name='شنبه تا چهارشنبه')),
                ('working_hours_thu', models.CharField(blank=True, max_length=50, verbose_name='پنجشنبه')),
                ('working_hours_fri', models.CharField(default='تعطیل', max_length=50, verbose_name='جمعه')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='توضیحات متای سئو')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ستون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ستون فوتر',
                'verbose_name_plural': 'ستون\u200cهای فوتر',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام منو')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منوها',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مشترک خبرنامه',
                'verbose_name_plural': 'مشترکین خبرنامه',
            },
        ),
        migrations.CreateModel(
            name='SidebarBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('position', models.CharField(choices=[('blog', 'وبلاگ'), ('category', 'دسته\u200cبندی'), ('detail', 'جزئیات محصول')], max_length=50, verbose_name='موقعیت نمایش')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بنر سایدبار',
                'verbose_name_plural': 'بنرهای سایدبار',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SidebarWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ویجت')),
                ('position', models.CharField(choices=[('blog', 'وبلاگ'), ('category', 'دسته\u200cبندی'), ('detail', 'جزئیات محصول')], max_length=50, verbose_name='موقعیت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویجت سایدبار',
                'verbose_name_plural': 'ویجت\u200cهای سایدبار',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Voltom', max_length=100, verbose_name='نام سایت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('copyright_text', models.CharField(default='تمامی حقوق محفوظ است', max_length=200, verbose_name='متن کپی\u200cرایت')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فیس\u200cبوک')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('feature_1_icon', models.CharField(default='icon-truck', max_length=50, verbose_name='آیکون ویژگی ۱')),
                ('feature_1_text', models.CharField(default='ارسال سریع به سراسر ایران', max_length=100, verbose_name='متن ویژگی ۱')),
                ('feature_2_icon', models.CharField(default='icon-support', max_length=50, verbose_name='آیکون ویژگی ۲')),
                ('feature_2_text', models.CharField(default='ضمانت اصالت کالا', max_length=100, verbose_name='متن ویژگی ۲')),
                ('feature_3_icon', models.CharField(default='icon-money', max_length=50, verbose_name='آیکون ویژگی ۳')),
                ('feature_3_text', models.CharField(default='پشتیبانی تخصصی', max_length=100, verbose_name='متن ویژگی ۳')),
                ('feature_4_icon', models.CharField(default='icon-return', max_length=50, verbose_name='آیکون ویژگی ۴')),
                ('feature_4_text', models.CharField(default='گارانتی معتبر', max_length=100, verbose_name='متن ویژگی ۴')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='زیرعنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('button_text', models.CharField(blank=True, default='همین حالا خرید کنید', max_length=50, verbose_name='متن دکمه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('about', 'درباره ما'), ('terms', 'قوانین و شرایط')], max_length=20, unique=True, verbose_name='نوع صفحه')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='توضیحات متای سئو')),
                ('content', models.TextField(verbose_name='متن اصلی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='تصویر اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صفحه استاتیک',
                'verbose_name_plural': 'صفحات استاتیک',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('url', models.CharField(help_text='مثال: /about-us/ یا https://example.com', max_length=200, verbose_name='آدرس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footercolumn', verbose_name='ستون')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک\u200cهای فوتر',
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.menu', verbose_name='منو')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='زیرمنوی والد')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم\u200cهای منو',
                'ordering': ['order'],
            },
        ),
    ]
