# Generated by Django 6.0.6 on 2026-07-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0002_product_image_hover'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان بنر')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر بنر')),
                ('link', models.URLField(blank=True, verbose_name='لینک بنر')),
                ('position', models.CharField(choices=[('home_wide_1', 'صفحه اصلی - بنر عریض ۱'), ('home_wide_2', 'صفحه اصلی - بنر عریض ۲'), ('home_wide_3', 'صفحه اصلی - بنر عریض ۳'), ('home_wide_4', 'صفحه اصلی - بنر عریض ۴'), ('home_wide_big', 'صفحه اصلی - بنر بزرگ'), ('sidebar_blog', 'سایدبار وبلاگ'), ('sidebar_category', 'سایدبار دسته\u200cبندی'), ('sidebar_detail', 'سایدبار جزئیات محصول')], max_length=20, unique=True, verbose_name='موقعیت نمایش')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='متن روی بنر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بنر سایت',
                'verbose_name_plural': 'بنرهای سایت',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('hot_deals_title', 'عنوان بخش فروش ویژه'), ('special_offer_title', 'عنوان بخش پیشنهاد ویژه'), ('product_tags_title', 'عنوان بخش برچسب\u200cهای محصول'), ('special_deals_title', 'عنوان بخش تخفیف\u200cهای ویژه'), ('newsletter_title', 'عنوان بخش خبرنامه'), ('newsletter_desc', 'توضیحات خبرنامه'), ('new_products_title', 'عنوان بخش محصولات جدید'), ('featured_products_title', 'عنوان بخش محصولات ویژه'), ('featured_category_title', 'عنوان بخش لوازم برقی و الکترونیک'), ('latest_blog_title', 'عنوان بخش آخرین مقالات'), ('brands_title', 'عنوان بخش برندها')], max_length=50, unique=True, verbose_name='کلید بخش')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'عنوان بخش',
                'verbose_name_plural': 'عناوین بخش\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان منو')),
                ('page_type', models.CharField(choices=[('home', 'صفحه اصلی'), ('blog', 'وبلاگ'), ('about', 'درباره ما'), ('contact', 'تماس با ما'), ('products', 'همه محصولات'), ('terms', 'قوانین و شرایط'), ('comparison', 'مقایسه محصولات'), ('track', 'پیگیری سفارش'), ('custom', 'لینک دلخواه')], default='custom', max_length=20, verbose_name='نوع صفحه')),
                ('custom_url', models.CharField(blank=True, max_length=200, verbose_name='لینک دلخواه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='دسته\u200cبندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationmenu', verbose_name='زیرمنوی والد')),
            ],
            options={
                'verbose_name': 'منوی ناوبری',
                'verbose_name_plural': 'منوهای ناوبری',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
