# Generated by Django 6.0.6 on 2026-07-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitebanner_sitesection_remove_menuitem_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesection',
            name='section_key',
            field=models.CharField(choices=[('hot_deals_title', 'عنوان بخش فروش ویژه'), ('special_offer_title', 'عنوان بخش پیشنهاد ویژه'), ('product_tags_title', 'عنوان بخش برچسب\u200cهای محصول'), ('special_deals_title', 'عنوان بخش تخفیف\u200cهای ویژه'), ('newsletter_title', 'عنوان بخش خبرنامه'), ('newsletter_desc', 'توضیحات خبرنامه'), ('new_products_title', 'عنوان بخش محصولات جدید'), ('featured_products_title', 'عنوان بخش محصولات ویژه'), ('featured_category_title', 'عنوان بخش لوازم برقی و الکترونیک'), ('latest_blog_title', 'عنوان بخش آخرین مقالات'), ('brands_title', 'عنوان بخش برندها'), ('promo_text', 'متن تخفیف نوار منو')], max_length=50, unique=True, verbose_name='کلید بخش'),
        ),
    ]
